/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package q12transporte;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jaime
 */
public class VentInsCond extends javax.swing.JFrame {

    private ListaConductores Chofers = new ListaConductores();
    private String Accion;
    private Conductor mostCond;

    /**
     * Creates new form VentInsCond
     *
     * @param conduc
     * @param accion
     * @throws q12transporte.ExcepcionPersonal
     */
    public VentInsCond(ListaConductores conduc, String accion) throws ExcepcionPersonal {
        initComponents();
        this.Chofers = conduc;
        this.Accion = accion;
        jPbotonesNav.setVisible(false);
        if (Accion.equalsIgnoreCase("Listar")) {
            jPboton.setVisible(false);
            jPbotonesNav.setVisible(true);
            mostCond = Chofers.primer();
            jTnombre.setText(mostCond.getNombre());
            jTsalario.setText(String.valueOf(mostCond.getSalario()));
            jTnombre.setEditable(false);
            jTsalario.setEditable(false);
            jBant.setEnabled(false);
            jBprimero.setEnabled(false);
            jTpos.setText(String.valueOf(Chofers.pos()+1));
            jTpos.setEditable(false);
        }
    }

    /**
     * Pasar para buscar y mostrar
     *
     * @param conduc
     * @param accion
     * @param nombre
     * @throws q12transporte.ExcepcionPersonal
     */
    public VentInsCond(ListaConductores conduc, String accion, String nombre) throws ExcepcionPersonal {
        initComponents();
        this.Chofers = conduc;
        this.Accion = accion;
        jPbotonesNav.setVisible(false);
        if (Accion.equalsIgnoreCase("BuscaMuestra")) {
            mostCond = Chofers.devConductorNom(nombre);
            jTnombre.setText(mostCond.getNombre());
            jTsalario.setText(String.valueOf(mostCond.getSalario()));
            jTnombre.setEditable(false);
            jTsalario.setEditable(false);
            jBguardar.setText("Atras");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTnombre = new javax.swing.JTextField();
        jTsalario = new javax.swing.JTextField();
        jPbotonesNav = new javax.swing.JPanel();
        jBult = new javax.swing.JButton();
        jBsiguiente = new javax.swing.JButton();
        jBprimero = new javax.swing.JButton();
        jBant = new javax.swing.JButton();
        jTpos = new javax.swing.JTextField();
        jBatras = new javax.swing.JButton();
        jPboton = new javax.swing.JPanel();
        jBguardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Datos del conductor");

        jLabel2.setText("nombre");

        jLabel3.setText("salario");

        jBult.setIcon(new javax.swing.ImageIcon(getClass().getResource("/q12transporte/img/ult.png"))); // NOI18N
        jBult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBultActionPerformed(evt);
            }
        });

        jBsiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/q12transporte/img/sig.png"))); // NOI18N
        jBsiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsiguienteActionPerformed(evt);
            }
        });

        jBprimero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/q12transporte/img/pri.png"))); // NOI18N
        jBprimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBprimeroActionPerformed(evt);
            }
        });

        jBant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/q12transporte/img/ant.png"))); // NOI18N
        jBant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBantActionPerformed(evt);
            }
        });

        jBatras.setText("Atras");
        jBatras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBatrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPbotonesNavLayout = new javax.swing.GroupLayout(jPbotonesNav);
        jPbotonesNav.setLayout(jPbotonesNavLayout);
        jPbotonesNavLayout.setHorizontalGroup(
            jPbotonesNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPbotonesNavLayout.createSequentialGroup()
                .addGroup(jPbotonesNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPbotonesNavLayout.createSequentialGroup()
                        .addComponent(jBprimero)
                        .addGap(18, 18, 18)
                        .addComponent(jBant)
                        .addGap(18, 18, 18)
                        .addComponent(jTpos, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBsiguiente)
                        .addGap(18, 18, 18)
                        .addComponent(jBult, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPbotonesNavLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jBatras)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPbotonesNavLayout.setVerticalGroup(
            jPbotonesNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPbotonesNavLayout.createSequentialGroup()
                .addGroup(jPbotonesNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPbotonesNavLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPbotonesNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBult, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBsiguiente, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBant)
                            .addComponent(jBprimero, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPbotonesNavLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTpos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jBatras)
                .addContainerGap())
        );

        jBguardar.setText("Guardar");
        jBguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBguardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPbotonLayout = new javax.swing.GroupLayout(jPboton);
        jPboton.setLayout(jPbotonLayout);
        jPbotonLayout.setHorizontalGroup(
            jPbotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPbotonLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jBguardar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPbotonLayout.setVerticalGroup(
            jPbotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPbotonLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jBguardar)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTsalario, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPboton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPbotonesNav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTsalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addComponent(jPboton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPbotonesNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBguardarActionPerformed
        // TODO add your handling code here:
        if (Accion.equalsIgnoreCase("BuscaMuestra")) {
            this.dispose();
        } else {
            try {
                Chofers.insertar(new Conductor(jTnombre.getText(), Float.parseFloat(jTsalario.getText())));
                JOptionPane.showMessageDialog(null, "Conductor introducido", "Valido", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } catch (ExcepcionPersonal e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Tiene que ser numerico", "Error", JOptionPane.ERROR_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jBguardarActionPerformed

    private void jBsiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsiguienteActionPerformed
        try {
            // TODO add your handling code here:
            mostCond = Chofers.siguiente();
            jTnombre.setText(mostCond.getNombre());
            jTsalario.setText(String.valueOf(mostCond.getSalario()));
            jTpos.setText(String.valueOf(Chofers.pos()+1));
            if (Chofers.isPrimer()) {
                jBant.setEnabled(false);
                jBprimero.setEnabled(false);
            } else {
                jBant.setEnabled(true);
                jBprimero.setEnabled(true);
            }
            if (Chofers.isUltimo()) {
                jBsiguiente.setEnabled(false);
                jBult.setEnabled(false);
            } else {
                jBsiguiente.setEnabled(true);
                jBult.setEnabled(true);
            }
            
            
        } catch (ExcepcionPersonal ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBsiguienteActionPerformed

    private void jBantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBantActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            mostCond = Chofers.anterior();
            jTnombre.setText(mostCond.getNombre());
            jTsalario.setText(String.valueOf(mostCond.getSalario()));
            jTpos.setText(String.valueOf(Chofers.pos()+1));
            if (Chofers.isPrimer()) {
                jBant.setEnabled(false);
                jBprimero.setEnabled(false);
            } else {
                jBant.setEnabled(true);
                jBprimero.setEnabled(true);
            }
            if (Chofers.isUltimo()) {
                jBsiguiente.setEnabled(false);
                jBult.setEnabled(false);
            } else {
                jBsiguiente.setEnabled(true);
                jBult.setEnabled(true);
            }
        } catch (ExcepcionPersonal ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBantActionPerformed

    private void jBultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBultActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            mostCond = Chofers.ultimo();
            jTnombre.setText(mostCond.getNombre());
            jTsalario.setText(String.valueOf(mostCond.getSalario()));
            jTpos.setText(String.valueOf(Chofers.pos()+1));
            if (Chofers.isPrimer()) {
                jBant.setEnabled(false);
                jBprimero.setEnabled(false);
            } else {
                jBant.setEnabled(true);
                jBprimero.setEnabled(true);
            }
            if (Chofers.isUltimo()) {
                jBsiguiente.setEnabled(false);
                jBult.setEnabled(false);
            } else {
                jBsiguiente.setEnabled(true);
                jBult.setEnabled(true);
            }
        } catch (ExcepcionPersonal ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBultActionPerformed

    private void jBprimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBprimeroActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            mostCond = Chofers.primer();
            jTnombre.setText(mostCond.getNombre());
            jTsalario.setText(String.valueOf(mostCond.getSalario()));
            jTpos.setText(String.valueOf(Chofers.pos()+1));
            if (Chofers.isPrimer()) {
                jBant.setEnabled(false);
                jBprimero.setEnabled(false);
            } else {
                jBant.setEnabled(true);
                jBprimero.setEnabled(true);
            }
            if (Chofers.isUltimo()) {
                jBsiguiente.setEnabled(false);
                jBult.setEnabled(false);
            } else {
                jBsiguiente.setEnabled(true);
                jBult.setEnabled(true);
            }
        } catch (ExcepcionPersonal ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBprimeroActionPerformed

    private void jBatrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBatrasActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBatrasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBant;
    private javax.swing.JButton jBatras;
    private javax.swing.JButton jBguardar;
    private javax.swing.JButton jBprimero;
    private javax.swing.JButton jBsiguiente;
    private javax.swing.JButton jBult;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPboton;
    private javax.swing.JPanel jPbotonesNav;
    private javax.swing.JTextField jTnombre;
    private javax.swing.JTextField jTpos;
    private javax.swing.JTextField jTsalario;
    // End of variables declaration//GEN-END:variables
}
